<link rel="stylesheet" type="text/css" href="/lib/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/lib/css/bootstrap-theme.min.css" />
<link rel="stylesheet" type="text/css" href="/lib/css/bootstrap-formhelpers.min.css" />
<!--link rel="stylesheet" type="text/css" href="/lib/css/bootstrap.toastr.min.css" /-->

<script type="text/javascript" src="/lib/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/lib/js/bootstrap.min.js"></script>
<script type="text/javascript" scr="/lib/js/bootstrap-formhelpers.min.js"></script>
<!--script type="text/javascript" src="/lib/js/bootstrap.toastr.min.js"></script-->
<script type="text/javascript" src="/lib/js/jquery.cookie.js"></script>
