<link rel="stylesheet" type="text/css" href="/content/css/basic.css" />
<link rel="stylesheet" type="text/css" href="/content/css/sidenav.css" />
<link rel="stylesheet" type="text/css" href="/content/css/style.css" />
<link rel="stylesheet" type="text/css" href="/content/css/board.css" />
<link rel="stylesheet" type="text/css" href="/content/css/image.css" />

<script type="text/javascript" src="/content/js/genius_const.js"></script>
<script type="text/javascript" src="/content/js/genius_main.js"></script>
<script type="text/javascript" src="/content/js/genius_popup.js"></script>
<script type="text/javascript" src="/content/js/genius_func.js"></script>
<script type="text/javascript" src="/content/js/genius_bbs.js"></script>
<script type="text/javascript" src="/content/js/genius_page.js"></script>
